# Generated by Django 5.1.15 on 2026-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预算价格'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同价格'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_status',
            field=models.CharField(choices=[('draft', '草拟中'), ('pending_legal', '待法审'), ('pending_sign', '待签章'), ('signed', '已签署'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='合同签署状态'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('monthly', '人月型'), ('fixed', '项目制'), ('resource_pool', '资源池')], default='monthly', max_length=20, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', '计划中'), ('active', '进行中'), ('pending_acceptance', '待验收'), ('closed', '已结项')], default='planning', max_length=25, verbose_name='项目状态'),
        ),
    ]
