# Generated by Django 5.1.15 on 2026-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_budget_price_project_contract_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='consulting_direction',
            field=models.CharField(choices=[('core', '核心'), ('credit', '信贷'), ('credit_card', '信用卡'), ('payment', '支付'), ('channel', '渠道'), ('operations', '运营'), ('finance_accounting', '财会'), ('digital_transform', '数字化转型'), ('ai', '人工智能'), ('other', '其他')], default='other', max_length=30, verbose_name='咨询方向'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_domain',
            field=models.CharField(choices=[('overall_planning', '整体规划'), ('project_management', '项目管理'), ('professional_consulting', '专业咨询')], default='overall_planning', max_length=30, verbose_name='项目领域'),
        ),
    ]
