# Generated by Django 5.1.15 on 2026-06-19 14:07

from django.db import migrations
from django.contrib.auth.hashers import make_password


def seed_sysadmin(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    if User.objects.filter(username='sysadmin').exists():
        return

    User.objects.create(
        username='sysadmin',
        real_name='系统管理员',
        email='sysadmin@pmos.com',
        department='系统管理部',
        position='系统管理员',
        password=make_password('SysAdmin#2026'),
        is_superuser=True,
        is_staff=True,
        is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_sysadmin, migrations.RunPython.noop),
    ]
