# Generated by Django 5.1.15 on 2026-06-22 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_sysadmin'),
        ('projects', '0004_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='当前项目'),
        ),
    ]
