FROM ghcr.io/astral-sh/uv:0.7-python3.12

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN uv sync --no-install-project

COPY . .

RUN uv sync

EXPOSE 18001

CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "18001", "--reload"]
