apiVersion: v1
kind: Secret
metadata:
  name: pmos-secrets
  namespace: pmos
type: Opaque
stringData:
  mongo-username: admin
  mongo-password: change-me-in-production
  jwt-secret: change-me-in-production
  mongo-url: mongodb://pmos-mongodb:27017/pmos
