# Generated by Django 5.1.15 on 2026-06-18 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(blank=True, max_length=100, verbose_name='项目角色')),
                ('join_date', models.DateField(verbose_name='加入日期')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='离开日期')),
                ('allocation', models.IntegerField(default=100, verbose_name='投入比例(%)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='人员')),
            ],
            options={
                'verbose_name': '项目资源',
                'verbose_name_plural': '项目资源',
                'ordering': ['project', 'join_date'],
                'unique_together': {('project', 'user', 'join_date')},
            },
        ),
        migrations.CreateModel(
            name='ResourceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50, verbose_name='变更类型')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='变更详情')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='resources.projectresource', verbose_name='资源')),
            ],
            options={
                'verbose_name': '资源变更日志',
                'verbose_name_plural': '资源变更日志',
                'ordering': ['-changed_at'],
            },
        ),
    ]
