# Generated by Django 5.1.15 on 2026-06-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('rank', models.CharField(choices=[('director', '咨询总监'), ('senior', '高级咨询师'), ('consultant', '咨询师'), ('assistant', '咨询助理'), ('other', '其他')], default='consultant', max_length=30, verbose_name='职级')),
                ('status', models.CharField(choices=[('pending_entry', '待入场'), ('entered', '已入场'), ('pending_exit', '待离场'), ('exited', '已离场')], default='pending_entry', max_length=30, verbose_name='可用状态')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入场日期')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='离场日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '咨询人员',
                'verbose_name_plural': '咨询人员',
                'ordering': ['-created_at'],
            },
        ),
    ]
