# Generated by Django 5.1.15 on 2026-06-22 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_owner'),
        ('resources', '0002_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultants', to='projects.project', verbose_name='所属项目'),
        ),
    ]
