# Generated by Django 5.1.15 on 2026-06-18 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '沟通类型',
                'verbose_name_plural': '沟通类型',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CommRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='主题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('comm_date', models.DateTimeField(verbose_name='沟通时间')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_comms', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_comms', to=settings.AUTH_USER_MODEL, verbose_name='参与人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_records', to='projects.project', verbose_name='所属项目')),
                ('comm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.commtype', verbose_name='沟通类型')),
            ],
            options={
                'verbose_name': '沟通记录',
                'verbose_name_plural': '沟通记录',
                'ordering': ['-comm_date'],
            },
        ),
    ]
