# Generated by Django 5.1.15 on 2026-06-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='类型描述'),
        ),
        migrations.AddField(
            model_name='commtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
