# Generated by Django 5.1.15 on 2026-06-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_commtype_description_commtype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commtype',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='类型描述'),
        ),
    ]
