# Generated by Django 5.1.15 on 2026-06-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_commtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commrecord',
            name='conclusion',
            field=models.TextField(blank=True, default='', verbose_name='结论'),
        ),
    ]
