# Generated by Django 5.1.15 on 2026-06-22 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_commtype_project'),
        ('organizations', '0005_alter_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commrecord',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_comms', to='organizations.userorganization', verbose_name='发起人'),
        ),
        migrations.AlterField(
            model_name='commrecord',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_comms', to='organizations.userorganization', verbose_name='参与人'),
        ),
    ]
