# Generated by Django 5.1.15 on 2026-06-22 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('projects', '0004_alter_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.RemoveField(
            model_name='document',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='archive_status',
            field=models.CharField(choices=[('unarchived', '未归档'), ('archived', '已归档')], default='unarchived', max_length=20, verbose_name='归档状态'),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('report', '报告'), ('plan', '方案'), ('requirement', '需求'), ('minutes', '纪要'), ('other', '其他')], default='other', max_length=20, verbose_name='文档类型'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_format',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='文档格式'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='文档大小'),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上传时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传人'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='文档标题'),
        ),
        migrations.AlterField(
            model_name='document',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='文档版本'),
        ),
    ]
