# Generated by Django 5.1.15 on 2026-06-18 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('todo', '待办'), ('in_progress', '进行中'), ('done', '已完成'), ('closed', '已关闭')], default='todo', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='预估工时')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='实际工时')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['plan', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('type', models.CharField(choices=[('milestone', '里程碑'), ('group', '分组计划'), ('detail', '详细计划')], max_length=20, verbose_name='类型')),
                ('start_date', models.DateField(verbose_name='计划开始日期')),
                ('end_date', models.DateField(verbose_name='计划结束日期')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='实际结束日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '进行中'), ('completed', '已完成'), ('delayed', '已延期')], default='draft', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度(%)')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='plans.plan', verbose_name='上级计划')),
            ],
            options={
                'verbose_name': '计划',
                'verbose_name_plural': '计划',
                'ordering': ['project', 'sort_order', 'start_date'],
            },
        ),
    ]
