# Generated by Django 5.1.15 on 2026-06-20 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
        ('projects', '0004_alter_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stakeholders',
            field=models.TextField(blank=True, help_text='多个干系人用逗号分隔', verbose_name='干系人'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plans', to=settings.AUTH_USER_MODEL, verbose_name='责任人'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='计划描述'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划结束日期'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='计划开始日期'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('in_progress', '执行中'), ('suspended', '已挂起'), ('delayed', '已延期'), ('completed_late', '延期完成'), ('completed_on_time', '按期完成'), ('completed_early', '提前完成')], default='not_started', max_length=30, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('milestone', '里程碑计划'), ('middle', '中层计划'), ('detail', '详细计划')], max_length=20, verbose_name='类型'),
        ),
    ]
