# Generated by Django 5.1.15 on 2026-06-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_stakeholders_alter_plan_assignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='assignee',
        ),
        migrations.AddField(
            model_name='plan',
            name='assignee_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='责任人'),
        ),
    ]
