# Generated by Django 5.1.15 on 2026-06-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_plan_assignee_plan_assignee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stakeholders',
            field=models.TextField(blank=True, help_text='多个干系人用逗号分隔', verbose_name='干系人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('in_progress', '执行中'), ('suspended', '已挂起'), ('delayed', '已延期'), ('completed_late', '延期完成'), ('completed_on_time', '按期完成'), ('completed_early', '提前完成')], default='not_started', max_length=20, verbose_name='状态'),
        ),
    ]
