# Generated by Django 5.1.15 on 2026-06-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_task_stakeholders_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='负责人姓名'),
        ),
    ]
