# Generated by Django 5.1.15 on 2026-06-18 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='需求编号')),
                ('name', models.CharField(max_length=200, verbose_name='需求名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='来源')),
                ('priority', models.CharField(default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('proposed', '已提议'), ('approved', '已批准'), ('rejected', '已驳回'), ('deferred', '已推迟')], default='proposed', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_requirements', to='projects.project', verbose_name='所属项目')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '业务需求',
                'verbose_name_plural': '业务需求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='需求编号')),
                ('name', models.CharField(max_length=200, verbose_name='需求名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='功能模块')),
                ('priority', models.CharField(default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('proposed', '已提议'), ('approved', '已批准'), ('in_development', '开发中'), ('testing', '测试中'), ('completed', '已完成'), ('rejected', '已驳回')], default='proposed', max_length=20, verbose_name='状态')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='目标版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('business_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='software_requirements', to='requirements.businessrequirement', verbose_name='关联业务需求')),
            ],
            options={
                'verbose_name': '软件需求',
                'verbose_name_plural': '软件需求',
                'ordering': ['-created_at'],
            },
        ),
    ]
