# Generated by Django 5.1.15 on 2026-06-23 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_alter_department_manager'),
        ('projects', '0004_alter_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('business', '业务需求'), ('software_func', '软件功能需求'), ('software_perf', '软件性能需求'), ('other', '其他需求')], max_length=30, verbose_name='需求类型')),
                ('name', models.CharField(max_length=200, verbose_name='需求名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='需求描述')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='需求完成日期')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('document', models.FileField(blank=True, upload_to='requirements/', verbose_name='需求文档')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('pending_review', '待评审'), ('review_passed', '评审通过'), ('baselined', '纳入基线')], default='submitted', max_length=30, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='organizations.userorganization', verbose_name='需求负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='projects.project', verbose_name='所属项目')),
                ('review_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_requirements', to='organizations.userorganization', verbose_name='评审负责人')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '需求',
                'verbose_name_plural': '需求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('business', '业务需求'), ('software_func', '软件功能需求'), ('software_perf', '软件性能需求'), ('other', '其他需求')], max_length=30, verbose_name='需求类型')),
                ('name', models.CharField(max_length=200, verbose_name='基线名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='基线描述')),
                ('version', models.CharField(max_length=50, unique=True, verbose_name='基线版本')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_baselines', to='projects.project', verbose_name='所属项目')),
                ('requirements', models.ManyToManyField(related_name='baselines', to='requirements.requirement', verbose_name='基线需求')),
            ],
            options={
                'verbose_name': '需求基线',
                'verbose_name_plural': '需求基线',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_version', models.CharField(max_length=50, verbose_name='基线版本')),
                ('object_desc', models.TextField(verbose_name='变更对象')),
                ('content', models.TextField(verbose_name='变更内容')),
                ('approval_status', models.CharField(choices=[('pending', '待审批'), ('approved', '审批通过'), ('rejected', '审批不通过')], default='pending', max_length=20, verbose_name='审批状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_approvers', to='organizations.userorganization', verbose_name='变更审批人')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_assignees', to='organizations.userorganization', verbose_name='变更负责人')),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='requirements.requirementbaseline', verbose_name='所属基线')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '需求变更',
                'verbose_name_plural': '需求变更',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_method', models.CharField(choices=[('meeting', '会议'), ('email', '邮件'), ('circulation', '传签'), ('other', '其他')], max_length=20, verbose_name='评审方式')),
                ('review_date', models.DateField(verbose_name='评审日期')),
                ('conclusion', models.CharField(choices=[('pass', '通过'), ('conditional_pass', '有条件通过'), ('fail', '不通过')], max_length=30, verbose_name='评审结论')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('document', models.FileField(blank=True, upload_to='reviews/', verbose_name='评审文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='requirements.requirement', verbose_name='关联需求')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_reviews', to='organizations.userorganization', verbose_name='评审负责人')),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='participated_reviews', to='organizations.userorganization', verbose_name='评审干系人')),
            ],
            options={
                'verbose_name': '需求评审',
                'verbose_name_plural': '需求评审',
                'ordering': ['-created_at'],
            },
        ),
    ]
