# Generated by Django 5.1.15 on 2026-06-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementbaseline',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='基线版本'),
        ),
    ]
