# Generated by Django 5.1.15 on 2026-06-23 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_owner'),
        ('requirements', '0002_alter_requirementbaseline_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='requirementbaseline',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'version'), name='uq_baseline_project_name_version'),
        ),
    ]
