# Generated by Django 5.1.15 on 2026-06-19 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='投产名称')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版本号')),
                ('planned_date', models.DateTimeField(verbose_name='计划投产时间')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='实际投产时间')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('in_progress', '进行中'), ('completed', '已完成'), ('rolled_back', '已回滚'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('rollback_plan', models.TextField(blank=True, verbose_name='回滚方案')),
                ('result', models.TextField(blank=True, verbose_name='投产结果')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_deployments', to=settings.AUTH_USER_MODEL, verbose_name='指挥人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deployments', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_deployments', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '投产指挥',
                'verbose_name_plural': '投产指挥',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='演练名称')),
                ('planned_date', models.DateTimeField(verbose_name='计划演练时间')),
                ('actual_date', models.DateTimeField(blank=True, null=True, verbose_name='实际演练时间')),
                ('status', models.CharField(choices=[('planned', '待演练'), ('in_progress', '演练中'), ('completed', '已完成'), ('failed', '演练失败')], default='planned', max_length=20, verbose_name='状态')),
                ('checklist', models.JSONField(blank=True, default=list, verbose_name='检查项')),
                ('result', models.TextField(blank=True, verbose_name='演练结果')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drills', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('participants', models.ManyToManyField(blank=True, related_name='drill_participations', to=settings.AUTH_USER_MODEL, verbose_name='参与人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_drills', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '投产演练',
                'verbose_name_plural': '投产演练',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='步骤名称')),
                ('description', models.TextField(blank=True, verbose_name='步骤说明')),
                ('order', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='预计时长(分钟)')),
                ('output', models.TextField(blank=True, verbose_name='执行输出')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='releases.releasedeployment', verbose_name='所属投产')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='release_steps', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '投产步骤',
                'verbose_name_plural': '投产步骤',
                'ordering': ['deployment', 'order'],
            },
        ),
    ]
