# Generated by Django 5.1.15 on 2026-06-25 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_owner'),
        ('releases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releasestep',
            name='deployment',
        ),
        migrations.RemoveField(
            model_name='releasestep',
            name='executor',
        ),
        migrations.AlterModelOptions(
            name='releasedrill',
            options={'ordering': ['-created_at'], 'verbose_name': '投产演练', 'verbose_name_plural': '投产演练'},
        ),
        migrations.RemoveField(
            model_name='releasedrill',
            name='actual_date',
        ),
        migrations.RemoveField(
            model_name='releasedrill',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='releasedrill',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='releasedrill',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='releasedrill',
            name='planned_date',
        ),
        migrations.RemoveField(
            model_name='releasedrill',
            name='result',
        ),
        migrations.RemoveField(
            model_name='releasedrill',
            name='status',
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drill_assignees', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='attachment',
            field=models.FileField(blank=True, upload_to='drill_attachments/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='conclusion',
            field=models.CharField(choices=[('pass', '通过'), ('conditional_pass', '条件通过'), ('fail', '不通过'), ('pending', '待判定')], default='pending', max_length=20, verbose_name='演练结论'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='criteria',
            field=models.TextField(blank=True, default='', verbose_name='判定标准'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='演练描述'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='expected_results',
            field=models.TextField(blank=True, default='', verbose_name='预期结果'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='prerequisites',
            field=models.TextField(blank=True, default='', verbose_name='前置条件'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='scenario',
            field=models.CharField(choices=[('normal_deploy', '正常部署'), ('service_down', '服务宕机'), ('rollback', '异常回滚'), ('business_verify', '业务验证'), ('monitor_alert', '监控告警'), ('other', '其他')], default='normal_deploy', max_length=20, verbose_name='演练场景'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='stakeholders',
            field=models.ManyToManyField(blank=True, related_name='drill_stakeholders', to=settings.AUTH_USER_MODEL, verbose_name='干系人'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='steps',
            field=models.TextField(blank=True, default='', verbose_name='演练步骤'),
        ),
        migrations.AddField(
            model_name='releasedrill',
            name='target_environment',
            field=models.CharField(choices=[('test', '测试环境'), ('pre_prod', '预发布环境'), ('gray_release', '生产灰度环境'), ('other', '其他环境')], default='test', max_length=20, verbose_name='目标环境'),
        ),
        migrations.AlterField(
            model_name='releasedrill',
            name='name',
            field=models.CharField(max_length=300, verbose_name='演练名称'),
        ),
        migrations.AlterField(
            model_name='releasedrill',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='备注说明'),
        ),
        migrations.AlterField(
            model_name='releasedrill',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_drills', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='ReleasePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='计划名称')),
                ('release_type', models.CharField(choices=[('regular', '常规发布'), ('hotfix', '紧急修复'), ('non_functional', '非功能变更'), ('infrastructure', '基础设施变更')], default='regular', max_length=20, verbose_name='发布类型')),
                ('target_environment', models.CharField(choices=[('pre_prod', '预发布环境'), ('gray_release', '生产灰度环境'), ('production', '生产环境')], default='production', max_length=20, verbose_name='目标环境')),
                ('content', models.TextField(blank=True, default='', verbose_name='上线内容')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('attachment', models.FileField(blank=True, upload_to='plan_attachments/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_assignees', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='release_plans', to='projects.project', verbose_name='所属项目')),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='plan_stakeholders', to=settings.AUTH_USER_MODEL, verbose_name='干系人')),
            ],
            options={
                'verbose_name': '投产计划',
                'verbose_name_plural': '投产计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ReleaseDeployment',
        ),
        migrations.DeleteModel(
            name='ReleaseStep',
        ),
    ]
