# Generated by Django 5.1.15 on 2026-06-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_remove_releasestep_deployment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseplan',
            name='deployment_method',
            field=models.CharField(choices=[('cold_deploy', '停机冷部署'), ('online_deploy', '联机热部署')], default='cold_deploy', max_length=20, verbose_name='部署方式'),
        ),
        migrations.AddField(
            model_name='releaseplan',
            name='expected_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预期结束时间'),
        ),
        migrations.AddField(
            model_name='releaseplan',
            name='planned_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='计划开始时间'),
        ),
        migrations.AddField(
            model_name='releaseplan',
            name='related_system',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='关联系统'),
        ),
    ]
