# Generated by Django 5.1.15 on 2026-06-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_alter_project_owner'),
        ('requirements', '0003_requirementbaseline_uq_baseline_project_name_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('type', models.CharField(choices=[('functional', '功能测试'), ('api', '接口测试'), ('performance', '性能测试'), ('security', '安全测试'), ('other', '其他')], default='functional', max_length=20, verbose_name='用例类型')),
                ('module', models.CharField(blank=True, default='', max_length=100, verbose_name='所属模块')),
                ('test_steps', models.TextField(blank=True, default='', verbose_name='测试步骤')),
                ('expected_result', models.TextField(blank=True, default='', verbose_name='预期结果')),
                ('priority', models.CharField(choices=[('p0', 'P0-致命'), ('p1', 'P1-高'), ('p2', 'P2-中'), ('p3', 'P3-低')], default='p2', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('inactive', '停用'), ('discarded', '废弃')], default='active', max_length=20, verbose_name='用例状态')),
                ('test_document', models.FileField(blank=True, upload_to='testing/test_cases/', verbose_name='测试文档')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='projects.project', verbose_name='所属项目')),
                ('related_requirements', models.ManyToManyField(blank=True, to='requirements.requirement', verbose_name='关联需求')),
                ('requirement_baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.requirementbaseline', verbose_name='需求基线')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='缺陷名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='缺陷描述')),
                ('severity', models.CharField(choices=[('fatal', '致命'), ('serious', '严重'), ('normal', '一般'), ('suggestion', '建议')], default='normal', max_length=20, verbose_name='严重程度')),
                ('priority', models.CharField(choices=[('p0', 'P0-致命'), ('p1', 'P1-高'), ('p2', 'P2-中'), ('p3', 'P3-低')], default='p2', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('reproducing', '复现中'), ('located', '已定位'), ('retesting', '复测中'), ('suspended', '已挂起'), ('resolved', '已解决')], default='reproducing', max_length=20, verbose_name='缺陷状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_defects', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_defects', to='projects.project', verbose_name='所属项目')),
                ('related_test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testcase', verbose_name='关联用例')),
            ],
            options={
                'verbose_name': '测试缺陷',
                'verbose_name_plural': '测试缺陷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='环境名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='环境描述')),
                ('config_info', models.TextField(blank=True, default='', verbose_name='配置信息')),
                ('db_info', models.TextField(blank=True, default='', verbose_name='数据库信息')),
                ('address_info', models.TextField(blank=True, default='', verbose_name='地址信息')),
                ('status', models.CharField(choices=[('planned', '计划'), ('active', '启用'), ('inactive', '停用'), ('discarded', '废弃')], default='planned', max_length=20, verbose_name='环境状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_environments', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试环境',
                'verbose_name_plural': '测试环境',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('goal', models.TextField(blank=True, default='', verbose_name='计划目标')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_plan_assignees', to=settings.AUTH_USER_MODEL, verbose_name='测试负责人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='projects.project', verbose_name='所属项目')),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='test_plan_stakeholders', to=settings.AUTH_USER_MODEL, verbose_name='干系人')),
                ('test_cases', models.ManyToManyField(blank=True, to='testing.testcase', verbose_name='测试用例')),
                ('test_environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testenvironment', verbose_name='测试环境')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(blank=True, null=True, verbose_name='执行日期')),
                ('result', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('blocked', '阻塞'), ('skipped', '跳过')], default='pass', max_length=20, verbose_name='执行结果')),
                ('evidence', models.FileField(blank=True, upload_to='testing/evidences/', verbose_name='执行凭证')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='projects.project', verbose_name='所属项目')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testing.testcase', verbose_name='关联用例')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testing.testplan', verbose_name='计划名称')),
            ],
            options={
                'verbose_name': '测试执行',
                'verbose_name_plural': '测试执行',
                'ordering': ['-created_at'],
            },
        ),
    ]
