# Generated by Django 5.1.15 on 2026-06-18 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('precondition', models.TextField(blank=True, verbose_name='前置条件')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='测试步骤')),
                ('expected_result', models.TextField(blank=True, verbose_name='预期结果')),
                ('type', models.CharField(choices=[('functional', '功能测试'), ('performance', '性能测试'), ('security', '安全测试'), ('ui', 'UI测试'), ('api', '接口测试')], default='functional', max_length=20, verbose_name='类型')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='模块')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.softwarerequirement', verbose_name='关联需求')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '执行中'), ('completed', '已完成'), ('blocked', '已阻塞')], default='draft', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('blocked', '阻塞'), ('untested', '未执行')], default='untested', max_length=20, verbose_name='执行结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='testing.testcase', verbose_name='测试用例')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='testing.testplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '测试执行',
                'verbose_name_plural': '测试执行',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('severity', models.CharField(choices=[('critical', '致命'), ('major', '严重'), ('minor', '一般'), ('trivial', '轻微')], default='minor', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('new', '新建'), ('confirmed', '已确认'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='new', max_length=20, verbose_name='状态')),
                ('source', models.CharField(default='test', max_length=50, verbose_name='来源')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='模块')),
                ('version_found', models.CharField(blank=True, max_length=50, verbose_name='发现版本')),
                ('version_fixed', models.CharField(blank=True, max_length=50, verbose_name='修复版本')),
                ('resolution', models.CharField(blank=True, choices=[('fixed', '已修复'), ('duplicate', '重复'), ('not_a_bug', '非缺陷'), ('deferred', '延期处理')], max_length=20, null=True, verbose_name='解决方案')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='解决说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('related_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requirements.softwarerequirement', verbose_name='关联需求')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_bugs', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
                ('related_test_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testrun', verbose_name='关联测试执行')),
            ],
            options={
                'verbose_name': '缺陷',
                'verbose_name_plural': '缺陷',
                'ordering': ['-created_at'],
            },
        ),
    ]
