# Generated by Django 5.1.15 on 2026-06-18 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='设备编号')),
                ('type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='规格参数')),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '维护中'), ('retired', '已报废')], default='available', max_length=20, verbose_name='状态')),
                ('borrow_date', models.DateField(blank=True, null=True, verbose_name='借用日期')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='预计归还日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='借用人')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('annual', '年假'), ('sick', '病假'), ('personal', '事假'), ('marriage', '婚假'), ('maternity', '产假'), ('other', '其他')], max_length=20, verbose_name='请假类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('duration_days', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='天数')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('approve_notes', models.TextField(blank=True, verbose_name='审批意见')),
                ('cancel_date', models.DateField(blank=True, null=True, verbose_name='销假日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '请假',
                'verbose_name_plural': '请假',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='工时')),
                ('description', models.CharField(max_length=500, verbose_name='工作内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.task', verbose_name='任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL, verbose_name='人员')),
            ],
            options={
                'verbose_name': '工时',
                'verbose_name_plural': '工时',
                'ordering': ['-date'],
            },
        ),
    ]
