# Generated by Django 5.1.15 on 2026-06-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='设备数量'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='specs',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='设备规格'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('not_issued', '未出库'), ('in_use', '使用中'), ('recycled', '已回收'), ('scrapped', '已报废'), ('other', '其他')], default='not_issued', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('server', '服务器'), ('computer', '计算机'), ('printer', '打印机'), ('storage', '移动存储'), ('consumable', '耗材'), ('other', '其他')], default='other', max_length=30, verbose_name='设备类型'),
        ),
    ]
