# Generated by Django 5.1.15 on 2026-06-22 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_owner'),
        ('work_management', '0002_equipment_quantity_alter_equipment_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='备注说明'),
        ),
    ]
