# Generated by Django 5.1.15 on 2026-06-22 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_department_manager'),
        ('projects', '0004_alter_project_owner'),
        ('work_management', '0003_equipment_project_alter_equipment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='organizations.userorganization', verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='销假状态'),
        ),
        migrations.AddField(
            model_name='leave',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='备注说明'),
        ),
        migrations.AddField(
            model_name='leave',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='projects.project', verbose_name='所属项目'),
        ),
    ]
