# Generated by Django 5.1.15 on 2026-06-22 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_department_manager'),
        ('work_management', '0004_leave_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='approve_notes',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='cancel_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.AlterField(
            model_name='leave',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='organizations.userorganization', verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='duration_days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='天数'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('personal', '事假'), ('sick', '病假'), ('annual', '年假'), ('marriage', '婚假'), ('funeral', '丧假'), ('paternity', '陪产假'), ('compensatory', '调休假'), ('family_visit', '探亲假'), ('other', '其他')], max_length=20, verbose_name='请假类型'),
        ),
    ]
