# Generated by Django 5.1.15 on 2026-06-22 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_department_manager'),
        ('projects', '0004_alter_project_owner'),
        ('work_management', '0005_remove_leave_approve_notes_remove_leave_cancel_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-start_date'], 'verbose_name': '工时', 'verbose_name_plural': '工时'},
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='user',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approval_status',
            field=models.CharField(choices=[('approved', '同意'), ('returned', '退回'), ('rejected', '拒绝')], default='approved', max_length=20, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to='organizations.userorganization', verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='organizations.userorganization', verbose_name='填报人'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='type',
            field=models.CharField(choices=[('workday', '工作日'), ('holiday', '节假日'), ('overtime', '加班'), ('leave', '请假')], default='workday', max_length=20, verbose_name='工时类型'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], default='normal', max_length=20, verbose_name='工时状态'),
        ),
        migrations.CreateModel(
            name='TimesheetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('type', models.CharField(choices=[('workday', '工作日'), ('holiday', '节假日'), ('overtime', '加班'), ('leave', '请假')], max_length=20, verbose_name='工时类型')),
                ('hours', models.DecimalField(decimal_places=1, default=8.0, max_digits=4, verbose_name='工时')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='work_management.timesheet', verbose_name='工时记录')),
            ],
            options={
                'verbose_name': '工时明细',
                'verbose_name_plural': '工时明细',
                'ordering': ['date'],
                'unique_together': {('timesheet', 'date')},
            },
        ),
    ]
