# Generated by Django 5.1.15 on 2026-06-25 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_owner'),
        ('work_management', '0006_alter_timesheet_options_remove_timesheet_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='问题标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='问题描述')),
                ('issue_type', models.CharField(choices=[('plan_execution', '计划执行'), ('resource', '资源问题'), ('config_error', '配置错误'), ('change_request', '变更请求'), ('external_dependency', '外部依赖'), ('other', '其他')], default='other', max_length=30, verbose_name='问题类型')),
                ('severity', models.CharField(choices=[('fatal', '致命'), ('serious', '严重'), ('normal', '一般'), ('tip', '提示')], default='normal', max_length=20, verbose_name='严重程度')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('source', models.CharField(choices=[('exec_tracking', '执行跟踪'), ('user_feedback', '用户反馈'), ('other', '其他')], default='other', max_length=30, verbose_name='问题来源')),
                ('expected_resolution_date', models.DateField(blank=True, null=True, verbose_name='期望解决日期')),
                ('status', models.CharField(choices=[('new', '新建'), ('confirmed', '已确认'), ('analyzing', '分析中'), ('fixing', '修复/解决中'), ('pending_verify', '待验证'), ('closed', '已关闭'), ('reopened', '重新打开')], default='new', max_length=20, verbose_name='问题状态')),
                ('resolution', models.TextField(blank=True, default='', verbose_name='解决方案')),
                ('attachment', models.FileField(blank=True, upload_to='issue_attachments/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project', verbose_name='所属项目')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='issue_stakeholders', to=settings.AUTH_USER_MODEL, verbose_name='干系人')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='风险标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='风险描述')),
                ('category', models.CharField(choices=[('schedule', '进度'), ('requirement', '需求'), ('technology', '技术'), ('resource', '资源'), ('external_dependency', '外部依赖'), ('compliance', '合规'), ('other', '其他')], default='other', max_length=30, verbose_name='风险类别')),
                ('probability', models.CharField(choices=[('very_high', '很高'), ('high', '高'), ('medium', '中'), ('low', '低'), ('very_low', '很低')], default='medium', max_length=10, verbose_name='发生概率')),
                ('impact', models.CharField(choices=[('fatal', '致命'), ('serious', '严重'), ('normal', '一般'), ('slight', '轻微')], default='normal', max_length=10, verbose_name='影响程度')),
                ('risk_level', models.CharField(blank=True, choices=[('extreme', '极高'), ('high', '高'), ('medium', '中'), ('low', '低')], default='', max_length=10, verbose_name='风险等级')),
                ('early_signs', models.TextField(blank=True, default='', verbose_name='早期征兆')),
                ('strategy', models.CharField(choices=[('avoid', '规避'), ('transfer', '转移'), ('mitigate', '缓解'), ('accept', '接受')], default='accept', max_length=10, verbose_name='应对策略')),
                ('response_plan', models.TextField(blank=True, default='', verbose_name='应对计划')),
                ('status', models.CharField(choices=[('new', '新建'), ('assessing', '评估中'), ('planned', '已制定应对'), ('monitoring', '监控中'), ('closed', '已关闭')], default='new', max_length=20, verbose_name='风险状态')),
                ('attachment', models.FileField(blank=True, upload_to='risk_attachments/', verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_risks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project', verbose_name='所属项目')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_risks', to=settings.AUTH_USER_MODEL, verbose_name='报告人')),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='risk_stakeholders', to=settings.AUTH_USER_MODEL, verbose_name='干系人')),
            ],
            options={
                'verbose_name': '风险',
                'verbose_name_plural': '风险',
                'ordering': ['-created_at'],
            },
        ),
    ]
