# Generated by Django 5.1.15 on 2026-06-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_department_description'),
        ('resources', '0002_consultant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userorganization',
            options={'ordering': ['department', 'name'], 'verbose_name': '组织成员', 'verbose_name_plural': '组织成员'},
        ),
        migrations.AlterUniqueTogether(
            name='userorganization',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_memberships', to='resources.consultant', verbose_name='资源'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='project_role',
            field=models.CharField(blank=True, choices=[('project_director', '项目总监'), ('project_manager', '项目经理'), ('consulting_expert', '咨询专家'), ('consulting_advisor', '咨询顾问'), ('consulting_assistant', '咨询助理'), ('other', '其他')], max_length=50, verbose_name='项目岗位'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='rank',
            field=models.CharField(blank=True, max_length=30, verbose_name='职级'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='joined_at',
            field=models.DateField(blank=True, null=True, verbose_name='加入日期'),
        ),
        migrations.RemoveField(
            model_name='userorganization',
            name='is_leader',
        ),
        migrations.RemoveField(
            model_name='userorganization',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userorganization',
            name='user',
        ),
    ]
