# Generated by Django 5.1.15 on 2026-06-22 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_userorganization_options_and_more'),
        ('projects', '0004_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_members', to='projects.project', verbose_name='所属项目'),
        ),
    ]
