# Generated by Django 5.1.15 on 2026-06-22 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_department_project_userorganization_project'),
        ('resources', '0003_consultant_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='resources.consultant', verbose_name='部门负责人'),
        ),
    ]
